# Generated by Django 5.2.3 on 2025-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(choices=[('booking', 'Бронирование столика'), ('delivery', 'Доставка'), ('catering', 'Кейтеринг'), ('feedback', 'Отзыв'), ('other', 'Другое')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gramms', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_type', models.CharField(choices=[('main', 'Основное меню'), ('banquet', 'Банкетное меню')], default='main', max_length=20)),
                ('available_at_restaurant', models.CharField(choices=[('available', 'Доступно'), ('unavailable', 'Недоступно'), ('coming_soon', 'Скоро будет'), ('special', 'Специальное'), ('seasonal', 'Сезонное'), ('popular', 'Популярное'), ('new', 'Новое')], default='available', max_length=255)),
                ('type_group_menu', models.CharField(choices=[('salad', 'Салаты'), ('cold_dish', 'Холодные закуски'), ('soup', 'Супы'), ('hot_dish', 'Горячее'), ('garnish', 'Гарниры, соусы'), ('beer', 'К пиву'), ('dessert', 'Десерты'), ('konditer', 'Кондитерские изделия'), ('drink', 'Горячие напитки'), ('non_alcoholic_drink', 'Безалкогольные напитки'), ('sok', 'Соки. Напитки'), ('energetic_drink', 'Энергетический напиток'), ('other', 'Другое')], default='other', max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('what_cuisine_dish', models.CharField(choices=[('traditional', 'Традиционная'), ('belarussian', 'Белорусская кухня')], default='traditional', max_length=255)),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
