# Generated by Django 5.2.3 on 2025-07-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuView', '0002_feedback_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
